image: node:alpine

stages:
  - build
  - deploy

cache:
  paths:
    - ./node_modules

project build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts: 
    paths:
      - ./build

deploy surge:
  stage: deploy
  script:
    - npm install -g surge
    - surge --project ./build --domain ${PUBLISH_DOMAIN}
